# Generated by Django 6.0.7 on 2026-07-16 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='skillalias',
            name='language',
            field=models.CharField(choices=[('UNSPECIFIED', 'Unspecified'), ('EN', 'English'), ('NE_ROMANIZED', 'Romanized Nepali')], default='UNSPECIFIED', max_length=20),
        ),
        migrations.CreateModel(
            name='UnmatchedSkillTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_term', models.CharField(max_length=150)),
                ('normalized_term', models.CharField(max_length=150, unique=True)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('best_candidate_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('best_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unmatched_candidates', to='taxonomy.skilltag')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_unmatched_terms', to=settings.AUTH_USER_MODEL)),
                ('resolved_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_from_unmatched', to='taxonomy.skilltag')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unmatched_skill_terms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurrence_count', '-updated_at'],
                'indexes': [models.Index(fields=['status'], name='taxonomy_un_status_464029_idx')],
            },
        ),
    ]
