# Generated by Django 6.0.7 on 2026-07-17 01:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_employerprofile_address_employerprofile_latitude_and_more'),
        ('taxonomy', '0003_consolidate_duplicate_skill_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('required_experience_years', models.PositiveSmallIntegerField(default=0)),
                ('wage_type', models.CharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('MONTHLY', 'Monthly'), ('FIXED', 'Fixed')], default='DAILY', max_length=20)),
                ('wage_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('work_type', models.CharField(choices=[('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('CONTRACT', 'Contract'), ('ONE_TIME', 'One-time')], default='ONE_TIME', max_length=20)),
                ('scheduled_datetime', models.DateTimeField(blank=True, help_text='Date/time the work is required to start, if applicable.', null=True)),
                ('duration_days', models.PositiveIntegerField(blank=True, help_text='Expected duration of the work in days, if applicable.', null=True)),
                ('number_of_workers_required', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_posts', to='taxonomy.category')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='profiles.employerprofile')),
                ('preferred_skills', models.ManyToManyField(blank=True, related_name='preferred_by_jobs', to='taxonomy.skilltag')),
                ('required_skills', models.ManyToManyField(blank=True, related_name='required_by_jobs', to='taxonomy.skilltag')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_posts', to='taxonomy.subcategory')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='jobs_jobpos_status_b64ac9_idx'), models.Index(fields=['category', 'subcategory'], name='jobs_jobpos_categor_775c84_idx')],
            },
        ),
    ]
