# Generated by Django 6.0.7 on 2026-08-22 04:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_employerprofile_address_employerprofile_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='worker_profile_photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
